### PR TITLE
Update project: Readme / best practice / .lock file

### PR DESCRIPTION
**Pull request by PatricNox**
> Replace 'echo' with 'print' for best practice usage

For terminal applications it's a better idea to use print. See
https://www.w3schools.com/php/php_echo_print.asp

> Update readme with proper setup instructions

Some steps that's required was missing.

> Commit .lock file

You should always commit the .lock file as it helps to version manage the packages, keeping project stable.

### CODE REVIEW

**Comment by peter279k** [comment]
Hi @PatricNox, thanks for your contributions.

According to your [reference](https://www.w3schools.com/php/php_echo_print.asp), I still don't know why the `print` is better than `echo` in terminal application.

Could you explain this in details? Thanks :).

**Comment by peter279k** [comment]
`composer.lock` file is good, but it means that this will cache the dependencies.

To keep dependencies latest stable, I prefer we don't add the `composer.lock` file on Git version control.

And I've added `"minimum-stability": "stable"` attribute on `composer.json`.

**Comment by PatricNox** [comment]
Hello!

`"minimum-stability": "stable"` is sadly not sufficient. If a package has been updated to a version that'd break the application, then every "new" user from that point on would not have a local version working due to this. Therefore,` .lock` file is always a good idea to commit.

Read more here https://dev.to/rafaelcg/versioning-or-not-the-file-composer-lock-3ki3

Regarding print vs echo, print is overall a more command line interface used command as it has a return value of 1 so it can be used in expressions. It's mostly a best practice change, nothing affected.


I hope this answers your questions from where this PR came from.

Have a great day!
PatricNox

**Comment by peter279k** [comment]
Hi @PatricNox. Thanks for your quick reply.

I agree with this PR after your explanation :).

**Pull request merged**
